### ISSUE TITLE
Change how casing is defined in templates

### ISSUE THREAD

**Issue by reesemclean** [reesemclean/blueprint#13]
I propose we change the template syntax from this:

```
{{nameKebabCase}}
```

to this

```
{{kebabCase name}}
```

For the content of of the template this can be done through helpers in handlebars.

We would need to write helpers for each of the casing methods and change the context being passed into the handlebars template from

```
{
    nameKebabCase: string;
    nameSnakeCase: string;
    namePascalCase: string;
    nameCamelCase: string;
}
```

to this:

```
{
    name: string
}
```

For the file name I think we could change it from `__namekebabcase__` to `__kebabCase_name__`. Better ideas?

This would enable adding casing support for custom fields if that was ever supported. This change should be made before the initial release so templates don't have to be changed.

**Comment by reesemclean** [comment]
@nguyenduyh33 I think this would be a good one for you to work on next.

**Comment by nguyenduyh33** [comment]
Sounds good. Will do.

**Comment by nguyenduyh33** [comment]
@reesemclean pushed to branch duy-change-casing for review.

Not sure what the standard GitHub workflow for working on an issue is...should I create a new pull request and link it to this issue at this point?  Or convert this issue into a pull request maybe?

**Comment by nguyenduyh33** [comment]
@reesemclean I made changes to the examples in a separate branch in the blueprint-examples project.  Will wait until this issue is closed before merging it.

I'll update the readme when I get home tonight and then create a pull request to close out this issue.
