### ISSUE TITLE
Doesn't support Windows paths

### ISSUE THREAD

**Issue by HeedfulCrayon** [reesemclean/blueprint#36]
Your extension uses the foward slash for the linux/unix based OS's, but for Windows it can't ever find the path to the blueprint-templates folder:
    No Templates found in C:\users\Nate\Documents\Work\Powershell/blueprint-templates

**Comment by reesemclean** [comment]
Yep you are totally right, we have hardcoded for posix-like paths. I think I have that all cleaned up but since I don't have windows won't be able to really test it out myself.

You can either test it out by using the branch referenced above or we should have a new version published to the marketplace where you can test it out soon.

**Comment by HeedfulCrayon** [comment]
Would you be able to compile this to a vsix file for me?  I have never compiled something for visual studio code before

**Comment by reesemclean** [comment]
Here try this out: 
[blueprint-1.3.0.vsix.zip](https://github.com/reesemclean/blueprint/files/1258296/blueprint-1.3.0.vsix.zip)

**Comment by HeedfulCrayon** [comment]
So I uninstalled the current version and installed this version via VSIX install and tried creating a new template.  Here is the error that I got 
![blueprintissue](https://user-images.githubusercontent.com/5224972/29793354-c3c8ae72-8c00-11e7-8045-28bf28c4f6b5.png)

**Comment by reesemclean** [comment]
Okay I missed one place. If you don't mind give it one more try:

[blueprint-1.3.0.vsix.zip](https://github.com/reesemclean/blueprint/files/1258405/blueprint-1.3.0.vsix.zip)

If this doesn't work I will try to find a windows computer I can debug on.

**Comment by HeedfulCrayon** [comment]
That worked.  You're the man!  Thanks!  BTW it works with powershell scripts if you want to add that as a supported language

**Comment by reesemclean** [comment]
That’s great, thanks for helping me debug that! I should be releasing a new version to the marketplace soon so you won’t have to use this custom build for long.

If there are any templates you could share to the examples repo (https://github.com/reesemclean/blueprint-examples) that would be helpful to share the word.

**Comment by HeedfulCrayon** [comment]
Here are some of my powershell examples.  I can't guarantee that they are formatted to best practice or anything though.
[powershell_examples.zip](https://github.com/reesemclean/blueprint/files/1261477/powershell_examples.zip)

**Comment by reesemclean** [comment]
A new version has been released with Windows support. Thanks again!
