### ISSUE TITLE
Failed to generate file from template with "}}}"

### ISSUE THREAD

**Issue by iyegoroff** [reesemclean/blueprint#39]
I've got "Parse error on line 1:" and no files were generated for template:
`import {Base{{pascalCase name}}} from 'test';`

**Comment by reesemclean** [comment]
Sorry about that. Can you try with a space between { and Base, and a space before the final }?

**Comment by iyegoroff** [comment]
Actually this is a handlebars issue - http://handlebarsjs.com/expressions.html#whitespace-control. Fixed it the following way:
`import {Base{{~pascalCase name~}}} from 'test';`
