### ISSUE TITLE
Alias of template instead of path

### ISSUE THREAD

**Issue by r3d9u11** [reesemclean/blueprint#47]
Hi. Is it possible to show some alias/title of template (or name of template's folder) instead of full path in templates list?

**Comment by nguyenduyh33** [comment]
This relates to the enhancement discussed in https://github.com/reesemclean/blueprint/issues/44

**Comment by reesemclean** [comment]
I have a pull request open and we should be able to get this enhancement released soon.

**Comment by r3d9u11** [comment]
@nguyenduyh33 @reesemclean thanks for answer and sorry for duplicate :)

**Comment by reesemclean** [comment]
No problem, Thanks!

**Comment by reesemclean** [comment]
Version 2.1.0 has been released which should address this.
