### ISSUE TITLE
Name without transformation

### ISSUE THREAD

**Issue by r3d9u11** [reesemclean/blueprint#51]
Hi. Is it possible to use target name without [transformation](https://github.com/reesemclean/blueprint#available-transforms)?

**Comment by reesemclean** [comment]
It is not currently possible. Can you describe an example use case where that would help out?

**Comment by fabrazer** [comment]
+1 for this feature request!

The variable {{name}} in the template file is replaced with the raw input. Same behavior is needed for the file name __name__.

**Comment by reesemclean** [comment]
This behavior is now supported in file/folder names and is in the latest release. Thanks for the feedback!
