### ISSUE TITLE
What is manifest.json?

### ISSUE THREAD

**Issue by r3d9u11** [reesemclean/blueprint#52]
Hi. I did noted file manifest.json at some samples. What is it? Is there description of these file?

**Comment by reesemclean** [comment]
You are right there is no documentation of this file currently. The idea for it is that you can stick it in your template folder and it unlocks some more customization.

There are only 2 options in the file right now:

key | Description of Use
------------ | -------------
suffixesToIgnoreInInput | If the value is "component" for instance, if user enters "My First Component" as the input -- "My First" will be used in the substitutions. This is to enable you to put "Component" in the template and not have to worry about the user entering it or not.
createFilesInFolderWithPattern | This one is possible now by just creating a top-level folder in your template. Previously we did not support folders within folders. I would not use this anymore.

**Comment by reesemclean** [comment]
Added documentation of manifest.json to Readme
