### ISSUE TITLE
Error when create from template which with image file 

### ISSUE THREAD

**Issue by achen224** [reesemclean/blueprint#55]
Steps:

1. Click "new file from template"
1. Choose a template with jpg or png inside
1. Enter name

Error:

Lexical error on line 1. Unrecognized text.
����JFIF��C
----^

svg is ok,but jpg & png will error
maybe an option to ignore file/foler analyze

**Comment by reesemclean** [comment]
Thanks for writing that up. I will take a look into getting us setup to skip non-text files!

**Comment by reesemclean** [comment]
I think I have a solution ready and should be able to release a new version in the next few days that fixes this.

**Comment by reesemclean** [comment]
Version 2.2.0 was just released with this fix. Thanks for reporting!
