### ISSUE TITLE
nesting {{helper name}} within {} causes parsing error

### ISSUE THREAD

**Issue by michaelleone** [reesemclean/blueprint#56]
G'day mate! Thanks for the insanely useful plugin, its awesome! 

However I can't get the pascalHelper to add my filename as my CSS class name (CSS Modules), have pictured below. Any suggestions, did I miss something obvious? Appears to be an issue with nesting the helper moustache within another set of curly braces?

Cheers, 

Mick

<img width="559" alt="screen shot 2018-06-25 at 5 25 49 pm" src="https://user-images.githubusercontent.com/29173099/41862822-e13f07ba-789c-11e8-9bf9-f799f5e65041.png">
<img width="602" alt="screen shot 2018-06-25 at 5 26 01 pm" src="https://user-images.githubusercontent.com/29173099/41862824-e15d493c-789c-11e8-8a34-a0e7ccf6d049.png">

**Comment by michaelleone** [comment]
Hmmm, okay, it works with a space added after the helper moustache: 

`<div className={ styles.{{pascalCase name}} }>`

**Comment by michaelleone** [comment]
A suggestion! How about allowing use of VSCode user snippets in the template files? e.g. provide a placeholder for snippet names in the templates: {{snippetName: blahblah}}. That way the templates could be made as snippets including the curser positioning functions etc...

**Comment by michaelleone** [comment]
Still an issue really... Adding a space before and after the enclosing curly braces does solve the parsing issue however it results in compiled format of `className={ styles.FileName }` which STANDARD Linting dislikes (and I agree): 
<img width="327" alt="screen shot 2018-06-29 at 1 32 02 pm" src="https://user-images.githubusercontent.com/29173099/42092432-d563b33a-7ba0-11e8-9aea-4e3e0e7b0ef9.png">

**Comment by reesemclean** [comment]
Hmm... I will take look over the weekend. We use handlebars internally so if you find a solution related to that it should work here.

**Comment by michaelleone** [comment]
kk will look into it!
 
 
 
>  
>  
>

**Comment by reesemclean** [comment]
Here's the solution: http://handlebarsjs.com/expressions.html#whitespace-control

`<div className={ styles.{{pascalCase name~}} }>`

☝️ should do it. The ~ tells it to remove the whitespace the tag is replaced! Gonna close this out.
