### ISSUE TITLE
Vue component template bug

### ISSUE THREAD

**Issue by yarkovaleksei** [reesemclean/blueprint#58]
Create a Vue template component:
```html
<template>
   <div class="{{snakeCase name}}">
     {{msg}}
   </div>
</template>
```

As a result, the line `{{msg}}` disappears, although it does not refer to the name of the component.
```html
<template>
  <div class="component_name">
    
  </div>
</template>
```

**Comment by reesemclean** [comment]
Blueprint uses Handlebars internally, can you try something like: 
https://stackoverflow.com/a/20570734

**Comment by yarkovaleksei** [comment]
Yes, exactly, your advice helped to correct the error.
Thank you. The issue can be closed.
