### ISSUE TITLE
Support THIS_IS_CONSTANT naming 

### ISSUE THREAD

**Issue by PinkyJie** [reesemclean/blueprint#59]
This is a great library, thanks for your work!

Is it possible to support the constant naming style like THIS_IS_CONSTANT?

**Comment by reesemclean** [comment]
Hey this looks a duplicate of #51 . I will close this one out and begin work on that issue. Thanks!

**Comment by reesemclean** [comment]
Sure what would you call that transform?

**Comment by reesemclean** [comment]
I have added it as {{upperSnakeCase name}}. It should be in the latest release. Thanks!

**Comment by PinkyJie** [comment]
@reesemclean thank you a lot for the fix, so responsive
