### ISSUE TITLE
extension API

### ISSUE THREAD

**Issue by WebFreak001** [reesemclean/blueprint#68]
hi, is there an API so that other extensions can register new templates in your extension? (at least for a window session of vscode) Preferably something allowing callbacks when the user wants to create them, so extensions can provide dynamic data such as latest versions of dependencies in a package descriptor.

See https://code.visualstudio.com/api/references/vscode-api#extensions

**Comment by reesemclean** [comment]
Hmm... so the template folder is just a folder of files so you could have another extension run and update the your template folder. There is nothing I know of that would allow the Blueprint extension to call another extension automatically though. But you could write your extension and run it manually.
