### ISSUE TITLE
Way to generate template on the command line?

### ISSUE THREAD

**Issue by JRJurman** [reesemclean/blueprint#76]
I'm currently using this extension and even have a dedicated project for use with it - https://github.com/Tram-One/tram-blueprints. What I would like to do, as part of a pipeline in this project, is generate a template, run linting and run tests - just to make sure everything passes.

Is there a way in a CI environment I can create a blueprint template so that I can run these tests and linting?

**Comment by reesemclean** [comment]
I have thought about extracting the file creation out into a command line utility and use that within the extension but right now I don't see anyway besides including the files from the Blueprint into your project. But they would need to be updated anytime the extension updates. At some point I plan on tackling the command line utility but until then I will close this issue out.
